### ISSUE TITLE
Check is broken on `frame-metadata`

### ISSUE THREAD

**Issue by TriplEight** [paritytech/cargo-unleash#50] opened 2021-08-02 10:10 UTC
[Ref CI job](https://gitlab.parity.io/parity/substrate/-/pipelines/150270), the error is

<details>

```
error[E0432]: unresolved imports `frame_metadata::DecodeDifferent`, `frame_metadata::DecodeDifferentArray`, `frame_metadata::DefaultByte`, `frame_metadata::DefaultByteGetter`, `frame_metadata::ErrorMetadata`, `frame_metadata::FunctionArgumentMetadata`, `frame_metadata::FunctionMetadata`, `frame_metadata::ModuleConstantMetadata`, `frame_metadata::ModuleErrorMetadata`

```

</details>

Now it's merged into master and that [means](https://github.com/paritytech/substrate/pull/9373#issuecomment-890897448) that on the next version bump we will release the broken packages.

I'll take care of removing the publishing job until the issue is fixed.

**Comment by gnunicorn** [comment] 2021-08-02 11:13
I think the problem is that we have conflicting `frame_metadata`  while the crate is being moved out. It has already been published as an rc1, but I dunno the current status about removing the conflict from the substrate repo. tagged @insipx , who is working on this.

**Comment by ascjones** [comment] 2021-08-02 14:41
Exactly, hence I have since yanked the the new version of `frame_metadata` for now. Once my PR is merged then `frame_metadata` will have been removed from `substrate` so I assume that this will resolve itself.

Apologies for this, I wasn't aware of how this would cause problems with the `unleash` check.

**Comment by gilescope** [comment] 2021-10-04 14:31
@ascjones your PR is now merge, so is maybe this check not broken any more?

**Comment by ascjones** [comment] 2021-10-04 14:57
It is. So just would need a new PR to restore the check.

**Closed** 2021-11-10 10:19 UTC
Labels: bug
